volumes:
  sock:
    driver: local

services:
  nginx:
    image: paulohrpinheiro/rinha-nginx:v37
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock:rw
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.19"
          memory: "20MB"

  api-1:
    hostname: api-1
    image: paulohrpinheiro/rinha-api:v37
    environment:
      - PORT=8080
      - RESOURCES_DIR=/resources
      - UNIX_SOCKET_DIR=/run/sock
      - GOGC=off
      - GOMEMLIMIT=150MiB
    networks:
      - rinha-net
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.405"
          memory: "165MB"

  api-2:
    hostname: api-2
    image: paulohrpinheiro/rinha-api:v37
    environment:
      - PORT=8080
      - RESOURCES_DIR=/resources
      - UNIX_SOCKET_DIR=/run/sock
      - GOGC=off
      - GOMEMLIMIT=150MiB
    networks:
      - rinha-net
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.405"
          memory: "165MB"

networks:
  rinha-net:
    driver: bridge
