services:
  proxy:
    image: paulohrpinheiro/rinha-proxy:v2
    ports:
      - "9999:9999"
    environment:
      - BACKENDS=http://api-1:8080,http://api-2:8080
      - PORT=9999
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"

  api-1:
    image: paulohrpinheiro/rinha-api:v2
    environment:
      - PORT=8080
      - RESOURCES_DIR=/resources
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165MB"

  api-2:
    image: paulohrpinheiro/rinha-api:v2
    environment:
      - PORT=8080
      - RESOURCES_DIR=/resources
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165MB"

networks:
  rinha-net:
    driver: bridge
